# Generated by Django 5.2.10 on 2026-04-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=20),
        ),
    ]
